aplacelikethis/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views

# Use app_name to organize URLs by application. Here we have only one at the moment.
# Best practice is to have a separate urls.py for each application.
app_name = 'aplacelikethis'

urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    # path('', views.PostListView.as_view(), name='post_list'),
    # path converters:
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_details,
         name='post_details'),
    path('<int:post_id>/share/',
         views.post_share,
         name='post_share'),
    path('tag/<slug:tag_slug>/',
         views.post_list,
         name='post_list_by_tag'),
    path('portfolio/',
         views.portfolio,
         name='portfolio'),
    path('about/',
         views.about,
         name='about'),
]

aplacelikethis_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('aplacelikethis/', include('aplacelikethis.urls', namespace='aplacelikethis')),
]

aplacelikethis/models.py
from aplacelikethis_django.settings import AUTH_PASSWORD_VALIDATORS
from django.db import models
from django.utils import timezone
# User model from Django authentication system. No need to create another User model!
from django.contrib.auth.models import User
# reverse allows you to build URLs by their name and pass optional parameters
from django.urls import reverse
# taggit is an addon to allow tagging of posts
from taggit.managers import TaggableManager

# objects is the default model manager, but you can add additional ones. PublishedManager
# filters only published posts.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=100)
    # unique_for_date just makes sure each slug is unique on a given date
    slug = models.SlugField(max_length=100, unique_for_date='publish')
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    # auto_now_add adds the date automatically.
    created = models.DateTimeField(auto_now_add=True)
    # auto_now updates the date when you save.
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default='draft')
    # Need to add objects here to keep it as the default
    objects = models.Manager()  # Default model manager
    published = PublishedManager()  # Published model manager
    tags = TaggableManager() # Allows you to work with tags on POST objects

    # Meta contains metadata, used here for sorting posts by published date in
    # descending order ('-publish')
    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    # Returns 'Canonical" (aka Preferred) URL
    # Use get_absolute_url in templates to link to specific posts
    def get_absolute_url(self):
        return reverse('aplacelikethis:post_details',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

aplacelikethis/forms.py
from django import forms
from django.forms import fields
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    # widget overrides the default HTML (input) element:
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

aplacelikethis/views.py
from typing import List
from django.core import paginator
from django.shortcuts import render, get_object_or_404
# Adding pagination to limit number of posts that appear at once:
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Adding class-based views:
from django.views.generic import ListView
# Adding to allow email:
from django.core.mail import send_mail
# Adding to allow tagging and aggregated counts of tags:
from taggit.models import Tag
from django.db.models import Count

from .forms import EmailPostForm, CommentForm
from .models import Post, Comment

# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 5  # This determines how many posts are going to show at once.
#     template_name = 'aplacelikethis/post/list.html'

def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    # If there's a tag slug, get the Tag object, then filter posts by tag.
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        # __in is a "field lookup"
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 5)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    # posts = Post.published.all()
    return render(request,
                  'aplacelikethis/post/list.html',
                  {'page': page,
                  'posts': posts,
                  'tag': tag})


def post_details(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    # Retrieve all comments on this post:
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create comment object (save), but don't save to db yet (commit=False):
            new_comment = comment_form.save(commit=False)
            # Assign current post to comment:
            new_comment.post = post
            # Save new comment to db:
            new_comment.save()
    else:
        # If it's not a POST (i.e., a GET), create a new comment_form:
        comment_form = CommentForm()        

    # Aggregation: Get tags for current post, find posts with the same tag, then order them.
    # flat=True "flattens" the returned results to an array.
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:5]

    return render(request,
                  'aplacelikethis/post/details.html',
                  {'post': post,
                  'comments': comments,
                  'new_comment': new_comment,
                  'comment_form': comment_form,
                  'similar_posts': similar_posts})

def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if (request.method == 'POST'):
        form = EmailPostForm(request.POST)
        if (form.is_valid()):
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url()
            )
            subject = f"{cd['name']} recommends you read " f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'admin@aplacelikethis.com',
            [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'aplacelikethis/post/share.html',
    {'post': post,
    'form': form,
    'sent': sent})

def portfolio(request):
    return render(request, 'aplacelikethis/portfolio.html')

def about(request):
    return render(request, 'aplacelikethis/about.html')

aplacelikethis/templates/aplacelikethis/about.html
{% extends "aplacelikethis/base.html" %}

{% block title %}Portfolio{% endblock %}

{% block content %}
<h1>About Me</h1>
"My father was a relentlessly self-improving boulangerie owner from Belgium with low grade narcolepsy and a penchant for buggery. My mother was a fifteen year-old French prostitute named Chloe with webbed feet.<br><br>

My father would womanize, he would drink. He would make outrageous claims like he invented the question mark. Sometimes, he would accuse chestnuts of being lazy. The sort of general malaise that only the genius possess and the insane lament.<br><br>

My childhood was typical. Summers in Rangoon, luge lessons. In the spring, we’d make meat helmets.<br><br>

When I was insolent, I was placed in a burlap bag and beaten with reeds – pretty standard, really. At the age of twelve, I received my first scribe.<br><br>

At the age of fourteen, a Zoroastrian named Vilma ritualistically shaved my testicles. At the age of 18, I went off to evil medical school. At the age of 25, I took up tap dancing. I wanted to be a quadruple threat — an actor, dancer…"
<br>
<h2><a href="https://www.linkedin.com/in/wbmays/" target="_blank">LinkedIn</a></h2>
<br>
<h2><a href="https://www.facebook.com/wbmays" target="_blank">Facebook</a></h2>
{% endblock %}

aplacelikethis/templates/aplacelikethis/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
    <!-- <link href="{% static 'css/aplacelikethis.css' %}" rel="stylesheet"> -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/aplacelikethis.css' %}"
    />
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Exo+2:wght@300&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    {% block nav %}
    <ul id="nav">
      <li>
        {% block nav-home %}<a href="/aplacelikethis/">Home</a>{% endblock %}
      </li>
      <!-- <li>{% block nav-about %}<a href="https://www.linkedin.com/in/wbmays/">About</a>{% endblock %}</li>
            <li>{% block nav-contact %}<a href="">Contact</a>{% endblock %}</li> -->
    </ul>
    {% endblock %}
    <div id="content">{% block content %} {% endblock %}</div>
    <div id="sidebar">
      <h2><a href="/aplacelikethis/">A Place Like This</a></h2>
      <p>My place on the web.</p>
      <h3>
        <a href="/aplacelikethis/about/">About Me</a>
      </h3>
      <h3>
        <a href="/aplacelikethis/portfolio/">Portfolio / Projects</a>
      </h3>
      <h3>
        <a href="https://www.aplacelikethis.com/" target="_blank"
          >More Links and Stuff and Things</a
        >
      </h3>
    </div>
  </body>
</html>

aplacelikethis/templates/aplacelikethis/portfolio.html
{% extends "aplacelikethis/base.html" %}

{% block title %}Portfolio{% endblock %}

{% block content %}
<h1>My Portfolio</h1>
<h2><a href="https://eskatonic.github.io/flashcards/" target="_blank">Spanish Flashcards</a></h2>
<h3>A simple Javascript-based game to improve your Spanish vocabulary skills.</h3>
<br>
<h2><a href="https://hgtti.herokuapp.com/" target="_blank">Hitchhiker's Guide to the Imperium</a></h2>
<h3>A React-based Map and Encyclopedia for the Traveller RPG.</h3>
<br>
<h2><a href="https://mybrarysei322.herokuapp.com/" target="_blank">Mybrary</a></h2>
<h3>A library tracking/inventory system developed with Express, React, and MongoDB.</h3>
{% endblock %}

aplacelikethis/templates/aplacelikethis/post/details.html
{% extends "aplacelikethis/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<h1>{{ post.title }}</h1>
<p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|linebreaks }}
<p>
    <a href="{% url 'aplacelikethis:post_share' post.id %}">Share This Post</a>
</p>

{% with comments.count as total_comments %}
<h2>
    <!-- pluralize will make comment plural if there's more than one! -->
    {{ total_comments }} comment{{ total_comments|pluralize }}
</h2>
{% endwith %}

<h2>Similar Posts</h2>
{% for post in similar_posts %}
<p>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
</p>
{% empty %}
No similar posts.
{% endfor %}

{% for comment in comments %}
<div class="comment">
    <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
    </p>
    {{ comment.body|linebreaks }}
</div>
{% empty %}
<p>There are currently no comments.</p>
{% endfor %}

{% if new_comment %}
<h2>Comment added!</h2>
{% else %}
<h2>Add comment.</h2>
<form method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Add Comment"></p>
</form>
{% endif %}

{% endblock %}

aplacelikethis/templates/aplacelikethis/post/list.html
{% extends "aplacelikethis/base.html" %}

{% block title %}A Place Like This{% endblock %}

{% block content %}

<h1>A Place Like This</h1>

{% if tag %}
<h2>Posts tagged with "{{ tag.name }}"</h2>
{% endif %}

{% for post in posts %}

<h2>
  <a href="{{ post.get_absolute_url }}">
      {{ post.title }} </a>
</h2>

<p class="tags">
    Tags:
    {% for tag in post.tags.all %}
<a href="{% url 'aplacelikethis:post_list_by_tag' tag.slug %}">
    {{ tag.name }}
</a>
{% if not forloop.last %}, {% endif %}
{% endfor %}
</p>

<p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>

{{ post.body|truncatewords:30|linebreaks }}

{% endfor %}

    {% include "pagination.html" with page=posts %}

{% endblock %}

aplacelikethis/templates/aplacelikethis/post/share.html
{% extends "aplacelikethis/base.html" %}

{% block title %}Share a Post{% endblock %}

{% block content %}
{% if sent %}
<h1>Email Sent!</h1>
<p>
    "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
</p>
{% else %}
<h1>Share "{{ post.title }}"</h1>
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Send">
</form>
{% endif %}
{% endblock %}

aplacelikethis/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>